# Generated by Django 5.0 on 2024-03-30 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welly', '0002_alter_worklist_assigned_specialist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklist',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
