# Generated by Django 5.0 on 2024-03-30 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welly', '0003_alter_worklist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklist',
            name='assigned_specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='welly.specialist'),
        ),
        migrations.AlterField(
            model_name='worklist',
            name='assignment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
