# Generated by Django 5.0 on 2024-03-31 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welly', '0005_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklist',
            name='manual_priority',
            field=models.CharField(blank=True, choices=[('', 'Choose Priority'), ('H', 'High'), ('M', 'Medium'), ('L', 'Low')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='worklist',
            name='status',
            field=models.CharField(blank=True, choices=[('O', 'Ok'), ('P', 'Pending'), ('R', 'Reviewed'), ('E', 'Re-Review'), ('C', 'Closed')], default='P', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='worklist',
            name='sys_priority',
            field=models.CharField(blank=True, choices=[(0, 'Ok'), (1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Very High')], max_length=1000),
        ),
    ]
