# Generated by Django 5.0 on 2024-03-31 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welly', '0006_alter_worklist_manual_priority_alter_worklist_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklist',
            name='sys_priority',
            field=models.CharField(blank=True, choices=[('O', 'Ok'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('V', 'Very High')], max_length=1000),
        ),
    ]
