# Generated by Django 5.0 on 2024-03-31 13:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welly', '0007_alter_worklist_sys_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklist',
            name='diagnosis',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(default=dict, null=True), null=True, size=None),
        ),
        migrations.AddField(
            model_name='worklist',
            name='medications',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(default=dict, null=True), null=True, size=None),
        ),
        migrations.AddField(
            model_name='worklist',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worklist',
            name='services',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(default=dict, null=True), null=True, size=None),
        ),
    ]
