# Generated by Django 5.0 on 2024-03-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welly', '0008_worklist_diagnosis_worklist_medications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worklist',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='worklist',
            name='medications',
        ),
        migrations.RemoveField(
            model_name='worklist',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='worklist',
            name='services',
        ),
        migrations.AlterField(
            model_name='worklist',
            name='manual_priority',
            field=models.CharField(blank=True, choices=[('', 'Choose Priority'), ('high', 'High'), ('med', 'Medium'), ('low', 'Low')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='worklist',
            name='status',
            field=models.CharField(blank=True, choices=[('ok', 'Ok'), ('pending', 'Pending'), ('reviewed', 'Reviewed'), ('re-reviewed', 'Re-Review'), ('closed', 'Closed')], default='P', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='worklist',
            name='sys_priority',
            field=models.CharField(blank=True, choices=[('0', 'Ok'), ('1', 'Low'), ('2', 'Medium'), ('3', 'High'), ('4', 'Very High')], max_length=1000),
        ),
    ]
